export const LICHSUDATVE_REQUEST = "LICHSUDATVE_REQUEST";
export const LICHSUDATVE_SUCCESS = "LICHSUDATVE_SUCCESS";
export const LICHSUDATVE_FAIL = "LICHSUDATVE_FAIL";

export const LAYDANHSACHRAP = "LAYDANHSACHRAP";
