export const FETCH_SEATPLAN_REQUEST = "FETCH_SEATPLAN_REQUEST";
export const FETCH_SEATPLAN_SUCCESS = "FETCH_SEATPLAN_SUCCESS";
export const FETCH_SEATPLAN_FAIL = "FETCH_SEATPLAN_FAIL";

export const FETCH_CHONGHE = "FETCH_CHONGHE" ;

export const DATVE = "DATVE"